### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by jrusbatch** [ritterim/permissions#11]
* [x] #12: Add a build script to the solution
* [x] #13: Configure TeamCity to run the build script for each pull request
* [x] #14: Publish merges into master to NuGet
